### ISSUE TITLE
ImportError: cannot import name 'cython_nms' from 'maskrcnn_benchmark.layers.cython.nms'

### ISSUE THREAD

**Issue by Acekang** [siml3/HL-Net#2]
I can't run your code because of this bug. Are you sure that uploaded all files?

**Comment by hesedjds** [comment]
I have the same issues. how do you fix it?

**Comment by hesedjds** [comment]
I've fixed it. 
First, install the setuptools: `conda install setuptools`.
Then, cd to the maskrcnn_benckmark/layers/cython_nms: `cd maskrcnn_benckmark/layers/cython_nms`.
Lastly, set up the cython_nms with developing modes using setuptools: `python setup.py develop`.

After then, you can install the maskrcnn_benchmark with install instruction in the readme.md.
